resources:
  - ../../base
patches:
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: test-nest

commonLabels:
  app: dev-test-nest
namespace: dev
configMapGenerator:
  - behavior: merge
    literals:
      - ENV=dev
    name: test-nest
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: 5h4k4r/test-nest-k8s
    newName: 5h4k4r/test-nest-k8s
    newTag: 6e1f2110fb5671c41a5ac067bb4ed03083c5e6d9
