resources:
- ../../base
patches:
- path: ingress-patch.yaml
  target:
    kind: Ingress
    name: rmq-test-nest

commonLabels:
  app: dev-rmq-test-nest
namespace: dev
configMapGenerator:
- behavior: merge
  literals:
  - ENV=dev
  name: rmq-test-nest
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 5h4k4r/rmq-test-nest
  newName: 5h4k4r/rmq-test-nest
  newTag: 4ea170894e832781a02baed16ee86e27b4ab12c3
