resources:
  - ../../base
commonLabels:
  app: dev-rmq-test-consumer
namespace: dev
configMapGenerator:
  - behavior: merge
    literals:
      - ENV=dev
    name: rmq-test-consumer
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: 5h4k4r/rmq-test-nest
    newName: 5h4k4r/rmq-test-nest
    newTag: c537787bb927bce57ebf69b173125e081f941f1a
