apiVersion: apps/v1
kind: Deployment
metadata:
  name: rmq-test-nest
spec:
  selector:
    matchLabels:
      app: rmq-test-nest
  template:
    metadata:
      labels:
        app: rmq-test-nest
    spec:
      containers:
        - name: rmq-test-nest
          imagePullPolicy: Always
          image: 5h4k4r/rmq-test-nest-k8s:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
          ports:
            - containerPort: 3000
