apiVersion: apps/v1
kind: Deployment
metadata:
  name: rmq-test-consumer
spec:
  selector:
    matchLabels:
      app: rmq-test-consumer
  template:
    metadata:
      labels:
        app: rmq-test-consumer
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - worker
      containers:
        - name: rmq-test-consumer
          imagePullPolicy: Always
          image: 5h4k4r/rmq-test-nest:latest
          resources:
            limits:
              memory: "50Mi"
              cpu: "100m"
          ports:
            - containerPort: 3000
