- op: replace
  path: /spec/rules/0/host
  value: staging.consumer.shakar.tech
- op: add
  path: /spec/tls
  value:
    - hosts:
        - staging.consumer.shakar.tech
      secretName: lets-encrypt-staging.consumer.shakar.tech
- op: add
  path: /metadata/annotations
  value:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
