resources:
  - ../../base
patches:
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: rmq-test-consumer

commonLabels:
  app: staging-rmq-test-consumer
namespace: staging
configMapGenerator:
  - behavior: merge
    literals:
      - ENV=staging
    name: rmq-test-consumer
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: 5h4k4r/rmq-test-nest
    newName: 5h4k4r/rmq-test-nest
    newTag: 6e1f2110fb5671c41a5ac067bb4ed03083c5e6d9
